export const VALUE = 'value';
export const ERROR = 'error';
export const REQUIRED_FIELD_ERROR = "O campo não pode estar vazio";
export const UFS = [
  'SP',
  'SC',
  'AM',
  'RO',
  'AC',
  'RR',
  'PA',
  'AP',
  'TO',
  'MA',
  'PI',
  'CE',
  'RN',
  'PB',
  'PE',
  'AL',
  'SE',
  'BA',
  'MG',
  'ES',
  'RJ',
  'PR',
  'SC',
  'RS',
  'MS',
  'MT',
  'GO',
  'DF'
];

export const clientes = {
  nome: localStorage.getItem('firstname'),
  sobrenome: localStorage.getItem('lastname'),
  email: localStorage.getItem('email'),
  contato: localStorage.getItem('contato'),
  cep: localStorage.getItem('cep'),
  logradouro: localStorage.getItem('logradouro'),
  numero: localStorage.getItem('numero'),
  complemento: localStorage.getItem('complemento'),
  bairro: localStorage.getItem('bairro'),
  localidade: localStorage.getItem('localidade'),
  uf: localStorage.getItem('uf'),
  cep2: localStorage.getItem('cep'),
  logradouro2: localStorage.getItem('logradouro2'),
  numero2: localStorage.getItem('numero'),
  complemento2: localStorage.getItem('complemento'),
  bairro2: localStorage.getItem('bairro'),
  localidade2: localStorage.getItem('localidade'),
  uf2: localStorage.getItem('uf'),
  cpf: localStorage.getItem('cpf'),
  dataNascimento: localStorage.getItem('dataNascimento'),
  rendaMensal: localStorage.getItem('rendaMensal'),
}